# Generated by Django 2.1.3 on 2018-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='distance',
            field=models.PositiveIntegerField(default=0, help_text='distance of journey in kilometers'),
            preserve_default=False,
        ),
    ]
