# Generated by Django 2.1.3 on 2018-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('registration_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
